spring:  
  application:
    name: discovery-service
    
---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
server:  
  port: ${PORT:8761}

---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
    metadataMap:
      zone: zone2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:  
  port: ${PORT:8762}